CREATE DATABASE bdjoomla;
CREATE USER 'nodo'@'localhost' IDENTIFIED BY '*Qwer1234*';
GRANT ALL PRIVILEGES ON bdjoomla.* TO 'nodo'@'localhost' IDENTIFIED BY '*Qwer1234*' WITH GRANT OPTION;
FLUSH PRIVILEGES;
